# Generated by Django 4.2.6 on 2023-10-05 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='disco',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nome', models.CharField(max_length=200)),
                ('Descricao', models.TextField()),
                ('Selo_fonografico', models.CharField(max_length=50)),
                ('Ano', models.PositiveIntegerField()),
                ('Pais', models.CharField(max_length=50)),
                ('Genero', models.CharField(max_length=100)),
                ('Quantidade', models.PositiveIntegerField()),
            ],
        ),
    ]
